DROP TABLE IF EXISTS book_log;

CREATE TABLE book_log(
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255),
  status VARCHAR(10) NOT NULL,
  assessment INTEGER NOT NULL,
  impression VARCHAR(2000)
) DEFAULT CHARACTER SET=utf8mb4;